#!/bin/sh
set -e
if [ $# -ne 2 ]; then
    echo "usage: $0 old-version new-version" 1>&2
    exit 1
fi

VERSION=common/version.go

sed "s/^const Version = \"$1\"$/const Version = \"$2\"/g" $VERSION \
        > $VERSION.new
if cmp $VERSION $VERSION.new 1>/dev/null 2>/dev/null; then
    echo "fatal: $VERSION seems to be unchanged" 1>&2
    exit 1
fi
mv $VERSION.new $VERSION

mv ChangeLog.md ChangeLog.md.old
echo "# botticelli $2 [`date +%Y-%m-%d`]" > ChangeLog.md
echo "" >> ChangeLog.md
cat ChangeLog.md.old >> ChangeLog.md
rm ChangeLog.md.old
